# Generated by Django 5.2.3 on 2025-06-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='phone',
            field=models.CharField(max_length=15),
        ),
    ]
